### ISSUE TITLE
Add instructions on Wiki for script setup

### ISSUE THREAD

**Issue by helio-frota** [cejug/hurraa#103]
Started on CEJUG mailing list:
https://groups.google.com/d/msg/cejug/f4A58p-zrL8/3_C3oNcNtRQJ

**Comment by paulojribp** [comment]
Hi @eprogramming. I rename the issue for what we decide in refer discussion. Right?

**Comment by helio-frota** [comment]
@paulojribp  +1

**Comment by helio-frota** [comment]
@paulojribp  ok, tem como comitar no wiki ?
@clairtonluz precisa add a doc do script toda no padrão remember EsmerilProgramming !.

**Comment by paulojribp** [comment]
Reopening only because the wiki page doesn't follow the project default language, English. Anyone can do it or your self @eprogramming. After that, you can refer the page (https://github.com/cejug/hurraa/wiki/Shell-script-Wildfly-Setup) in the Home (https://github.com/cejug/hurraa/wiki). 

A little delay but responding your previous question: Yes, you can made a `git clone git@github.com:cejug/hurraa.wiki.git` so you can fix and push the wiki as code :)

**Comment by helio-frota** [comment]
will be done until end of this week.
