### ISSUE TITLE
Add button - Which position to adopt?

### ISSUE THREAD

**Issue by diogodias86** [cejug/hurraa#118]
I saw that in the page of equipment list, the position of "Add" button it is different than others pages. Which page it is correct? I prefer the page of equipment list.

**Comment by efraimgentil** [comment]
Hi Diogo, are you using the last version of Hurraa?, i searched for those difference but find nothing, some versions ago really had this difference, but i was already corrected.

Can you send a screenshot ?

**Comment by diogodias86** [comment]
Hi, Efraim. The images:
![image](https://f.cloud.github.com/assets/315828/2366641/1cc8aea8-a714-11e3-84e3-49efe288a6a9.png)
![image2](https://f.cloud.github.com/assets/315828/2366642/3f305586-a714-11e3-9978-b0ca1e3d8d90.png)

I'm sorry, but where i see the version of the app?

**Comment by danielsoro** [comment]
Do you following this pattern:

``` html
<a href="${linkTo[EquipmentTypeController].form}" 
class="btn btn-primary btn-sm" role="button">
```

?

**Comment by efraimgentil** [comment]
Yes this is it, actually this was already corrected, there is no functionality to show the version of the application, because we don't have a fully functional version yet, but you can open a issue to this, good point!

So you need to update your repository to the latest commit on github. you can follow the instructions o this link to achieve this
https://github.com/cejug/hurraa/wiki/How-use-git-properly-in-an-open-source-project

**Comment by diogodias86** [comment]
Hi, i updated my repository and worked! I'll open a issue for the functionality to show the version.
