### ISSUE TITLE
Change menu name from issue to Incident

### ISSUE THREAD

**Issue by helio-frota** [cejug/hurraa#78]
http://en.wikipedia.org/wiki/Incident_management_%28ITSM%29

**Comment by paulojribp** [comment]
@eprogramming Issue is a technologic word. I think this is correct, don't need to change. Hurraa is for technologic resources. From your link, see the example:

Examples[edit]

Incidents should be classified as they are recorded, Examples of incidents by classification are:
Application
service not available
data issue
application bug
disk-usage threshold exceeded
Hardware
system-down (server issue)
network issue
automatic alert
printer not printing
system issues

**Comment by helio-frota** [comment]
@paulojribp 

Based on:
http://en.wikipedia.org/wiki/Incident_management_%28ITSM%29

Please look:
http://blog.emporio-web.com/lang/pt-pt/2009/10/ocomon-gestao-de-incidentes-helpdesk-management-software/
http://www.profissionaisti.com.br/2009/01/ocomon-alternativa-livre-para-montar-o-seu-helpdesk/

**Comment by htmfilho** [comment]
I think `Incident` is the word used in this kind of system. We use one here that also designates problems reported by IT users as incidents. The word `issue` is more common in software development mainly due to Jira success. `Issue` is a bit confusing because this word is also used to register application improvements (which is not an issue).

**Comment by paulojribp** [comment]
Great, so lets move on.
