### ISSUE TITLE
Apply picketlink 

### ISSUE THREAD

**Issue by helio-frota** [cejug/hurraa#86]
https://groups.google.com/d/msg/cejug/kFH82tqjfug/V-aEYXm9o1QJ

**Comment by htmfilho** [comment]
I suggest PicketLink instead. The JAAS security implementation is cool in the Java code, but since the security configuration is veeeeery different from server to server, it's better use a framework to simplify the configuration and enable portability. I think PicketLink is the closest one to the JAAS specification. It uses CDI for authorization.

**Comment by helio-frota** [comment]
I found this right now 
https://github.com/dipold/vraptor-shiro
but never used shiro before what you think ?

**Comment by helio-frota** [comment]
https://www.jboss.org/picketlink
PicketLink is an important project under the security offerings from JBoss. 
Ok you found first for me whatever, no problem lets start... picketlink +1

**Comment by danielsoro** [comment]
Picketlink +1

**Comment by italocosta** [comment]
Picketlink +1

**Comment by helio-frota** [comment]
Thanks now is picketlink.

**Comment by paulojribp** [comment]
Cool this vraptor plugin for Shiro, I unknown it. I hear very good things from Shiro (http://shiro.apache.org/). Maybe we can make two branches, One with Shiro and other with Picketlink to see which one is simplest to use and portable.

**Comment by htmfilho** [comment]
... or VRaptor can increase its integration coverage creating a plugin for PicketLink ;-)

**Comment by felipewmartins** [comment]
Picketlink +1

**Comment by paulojribp** [comment]
What is the technical arguments to keep Picktlink instead of Shiro? I don't like decide only for feeling or because we like RedHat env more than Apache env. And if we use Picktlink, and more forward it cause trouble or do not support everything we want? Like TomEE do not support JAAS and JSF like we expect for Yougi.
I believe we need technical arguments to choice one instead other.

**Comment by htmfilho** [comment]
They are very much the same in terms of functionalities. I just don't feel comfortable using some Apache software, like TomEE, as you said.

But it's not true TomEE doesn't support JAAS and JSF. It support both, but I think the quality of those Apache components are inferior.

**Comment by helio-frota** [comment]
for now for me the most simple is the best

**Comment by helio-frota** [comment]
+1 para apache shiro vraptor plugin
https://github.com/dipold/vraptor-shiro/wiki/PT-BR-04.02.-Autoriza%C3%A7%C3%A3o

**Comment by paulojribp** [comment]
+100 :+1:

**Comment by helio-frota** [comment]
hi,
Unfortunately I can't work on this issue.
My laptop was stolen around ~2015 and I don't own this github handle: `eprogramming` anymore.
Also I don't remember a lot of java things.
